[project]
name = "data-generator"
version = "0.1.0"
description = "Generate sample data for testbed project"
requires-python = ">=3.13,<3.14"
dependencies = [
    "duckdb==1.4.4",
]

[tool.uv]
python-preference = "only-managed"